# Define the port where the API gateway server would be running
server:
  port: 8080

# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: 10.3.1.187
    port: 8899
    contextPath: userauth
    
# Define the routes which determine what URL are serviced by what applications.
# The application/services are defined in the bootstrap.yml file of individual applications
# using the spring.application.name property.

# Note that we don't proxy the calls to the authorization server. The reason being that 
# Spring cloud security would need to secure the api gateway before it can route the 
# requests using zuul
zuul:
  routes:
    bonus-server: 
      path: /bonus/**
      serviceId: bonus
      stripPrefix: false
    common: 
      path: /common/**
      serviceId: common
      stripPrefix: false
    games:
      path: /games/**
      serviceId: games
      stripPrefix: false
    gofiliate:
      path: /gofiliate/**
      serviceId: gofiliate
      stripPrefix: false
    seamless-gameart:
      path: /gameart/**
      serviceId: seamless-gameart
      stripPrefix: false
    auth-server: 
      path: /userauth/**
      stripPrefix: false
      serviceId: auth-server
# Define the Eureka server that handles service registration
eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.3.1.187:8761/eureka/
    
# Define settings for Single-Sign-On with OAuth2; this means that we need to relay the OAuth token 
# to the subsequent resources that are proxied by the Zuul api gateway.

# The home definition tells us to allow anonymous access (secure: false) to the static resources that
# are accessed through the Zuul proxy.

# Remaining properties are used by the OAuth2 SSO to determine where the authorization server is and
# what client crendentials to use to access that server.
spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /common/**,/gameart/**,/gofiliate/**, /games/**, /userauth/**, /userauth/oauth/**
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
      clientId: clientapp
      clientSecret: 123456a
# The userInfoUri is used to authenticate the user so that SSO token can be relayed forward. It needs to either be
# a physical endpoint (defined using userInfoUri) OR can be bypassed if you use a JSON web token (JWT) that stores
# information about grants and authentication in the token itself.

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
    
# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    url: jdbc:mysql://10.3.2.212:3306/core_indiana_oauth2
    username: testuser
    password: test13!Wkv
    driver-class: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    entitymanager-packagesToScan: com.microservice.mysql
    hibernate:
      ddl-auto: update
      useUnicode: true
      characterEncoding: utf8_bin
      charSet: UTF-8
      autoReconnect: true
      autoReconnectForPools: true
      c3p0:
         acquire_increment: 3
         max_size: 200
         min_size: 3
         maxIdleTime: 120
         unreturned_connection_timeout: 150
         timeout: 180
         maxConnectionAge: 120
         idle_test_period: 10
         maxStatements: 0
