# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8899
  contextPath: /userauth 

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.3.1.187:8761/eureka/

security:
  user:
    password: password      

# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    url: jdbc:mysql://10.3.2.182:3306/core_indiana_oauth2
    username: testuser
    password: test13!Wkv
    driver-class: com.mysql.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none


---

system_url:
  urlGameF1X2: http://vgames2875.com/f1x2games/loadGame.jsp
  
  urlGameMobileF1X2: http://vgames2875.com/f1x2games/loadMobileGame.jsp
  
  urlSevenSlotGame: http://games.sevenslot.net/
    

spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.3.1.187:8761/eureka/
