server:
  port: 8084 

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.3.1.187:8761/eureka/

security:
  basic:
    enabled: false
    
# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    url: jdbc:mysql://10.3.2.212:3306/core_indiana_oauth2
     username: testuser
     password: test13!Wkv
     driver-class: com.mysql.jdbc.Driver
   
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
